<Project Sdk="Microsoft.NET.Sdk">

	<PropertyGroup>
		<OutputType>WinExe</OutputType>
		<TargetFramework>net8.0-windows</TargetFramework>
		<Nullable>enable</Nullable>
		<UseWindowsForms>false</UseWindowsForms>
		<ApplicationIcon>mixlit.ico</ApplicationIcon>
		<AssemblyName>MixLit-Launcher</AssemblyName>
	</PropertyGroup>

	<PropertyGroup Condition="'$(Configuration)'=='Release'">
		<PublishSingleFile>true</PublishSingleFile>
		<SelfContained>true</SelfContained>
		<RuntimeIdentifier>win-x64</RuntimeIdentifier>
		<PublishTrimmed>true</PublishTrimmed>
		<EnableCompressionInSingleFile>true</EnableCompressionInSingleFile>
	</PropertyGroup>

</Project>